### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by patrickomeara** [slashequip/laravel-segment#6]
This is a very well-written package, well done. I'm wondering if it's still actively being maintained as #4 has been merged but not yet released.

If you are looking for maintainers I'm happy to help out.

**Comment by slashequip** [comment]
Hey @patrickomeara thanks for the kind words and you are right, I've be lacking a little in the maintenance department! You are more than welcome to help and contribute if this is something you'd like to do.

Are you using Segment or this package actively?

**Comment by patrickomeara** [comment]
I've been looking into segment, and I have implemented this package. Although I am re-evaluating my approach as I think I need a more granular event tracking system, where sales/marketing want to know different things to the dev team, in multiple destinations containing different metadata 😬 . So I am looking into laravel's event system to queue jobs to send to the different destinations as an alternative. I guess something similar to the notification channels.

One thing I really like about this package is sending the batch request after the response, that's a clever system. Well done.
